version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "dev"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "dependabot"
